### PR TITLE
Update tutorial lead description

### PR DESCRIPTION
**Pull request by hugocen**
I was unaware of the tick time and stuck in this tutorial.
So I think a hint to that might help with the new players.

### CODE REVIEW

**Comment by rlane** [comment]
Players aren't intended to need to use TICK_LENGTH in this tutorial. How did you use it?

**Comment by hugocen** [comment]
I calculated the turning angle and multiplied it by 60 (or  `/ TICK_LENGTH`).
I might get the whole calculation wrong but get lucky.

**Comment by hugocen** [comment]
@rlane here's my approach.
```
ENCRYPTED:AAwAAAAAAAAAlLWfYdknUUuBONxvngIAAAAAAADGy9R31b4iDxgOTiaa5xkpgqKQ2XhDdK5tsmWuen4i1NqQ+glD/Q7PW6+qX408QtQis3ThIFwXvqX9FhntVQSOs52/B/LmKW6NkZ6lBx9Iq+FbVtT/oTM5uafF6huEAVBP3RetfG4UUXn7VmTPqzxZdyDlf4LBNfvHTf7t2aXlM5LJOjqePlxDnGRkVuGXvy/LYiIq4T5PYHgJdHRXCoh1A5IItU/BZIGfxyCW51qfFImilEHm6luu4731Bdb7Xus0YAuY/RIQJou1aixk/ID5b7bkMGHW7ktZtfmhyNHRqrVdKBqEHPf6g+rKfp7bby9td3/VzjppIDd06yIHqMKRQorS1t8fnv8UfL1p1Fk+Ix4h3gJhKGKt0CWn7TL3NzMXdWgHvZc0AJMDHT86Ih3BCAIXcYHO0QJaG/fNqfB+qgR1jwYvPnxDymF9VTxHq8SPaHNS++ydFMWAVLAbkuPpA3DIXpjKs0hBrFsFRY0OT5USh43RN1RPjXKMDxAmRWLJxwPGPM901JghrEw3YCJz08SMEcbtky8BzgX3DbAuspNLJDWMyFYkd79fbbuLcaoz1AMjasfegnziBKhKGQCp+/SZ0IoEgqD5DHoGwD5v2+ZgC0NMTyqag2Uy6CjTAhh6GrKTUBpedAi+2D4QaNql4Y0SxrPHwoUPmJ0v4Df90LHxOPN3qRFRZb76jk51PJCFjwhF5Bpg0i+7NwmQ5JXbvTCLvCRGP6+AWG+sASea3rvFWMrb9fiktxoMqNUV9tmuCbDI8JK5wGO8qLW23JSulsgb+HutM/jE9VQrk2JGXNGF9E4/TmsvyjsmsJVlUtOnCqIsLWOyVYGtV0imNRzX5wSSq27q5dAt9G+7IsrB4ubaiF0gao9yZKeYZZSU
```

**Comment by hugocen** [comment]
hi @rlane do you think my approach is ok? Or did I get it by luck?
If it's only by luck then this PR will create confusion and I will close it.

**Pull request closed without merging**
