### PR TITLE
asteroid race scenario

### PR DESCRIPTION
**Pull request by t-fi**
Some open scenario design questions are:
- What should be the number and distribution of asteroids?
- Should the ship be able to fire guns/missile?

However there's a more crucial point: Radar somehow interferes with the `target()` function. Spawning a `fighter_without_missiles_or_radar` works fine. However when spawning a normal `fighter` , `target()` returns `0,0` by default. If an asteroid is in radar range, the asteroid position will be returned. So the ship cannot know where the actual target is 🤔

And of course, without radar the ship cannot know where the asteroids are. You can still try to figure it out by bouncing against them, but that is not the intended challenge 😄

Lastly I was thinking of adding bigger asteroids. AFAICT radar does not return target size yet, so that would require additional thoughts on "game design".

### CODE REVIEW

**Comment by rlane** [comment]
Looks good so far. I'd suggest:

1. Shrinking the world size so that the asteroids cover most of it.
2. Adding multiple waypoints.
3. Broadcasting the position of each waypoint on the corresponding radio channel.

**Comment by t-fi** [comment]
Yes, that sounds like a good way forward. Are you thinking of a world size and asteroid density like in gunnery?

**Comment by t-fi** [comment]
https://github.com/rlane/oort3/assets/16362866/941689f0-29dd-4eae-9fdc-ef61df0647fb

Here's how that currently looks:
- There are always three targets, pass them in any order to win
- Target locations can be obtained by listening to radio

Unfortunately, the tick execution order inside the simulator step makes it impossible to set the ship radar data from within the scenario tick. In between the radio ticks happen, and overwrite the scenario provided data.

Therefore each target also gets an enemy ship incl. AI, which will broadcast its initial position on randomly changing channels. The player can keep listening on one channel until all target positions are known. The initial player code already provides this boilerplate code. Ideally the data would just be on radio with no enemy ships.

A "bug", not sure if that must be tackled: The player ship does not do anything on the first run, one needs to rerun to make it move. Not sure what's going on there, could use some help with debugging this.

The reference AI is flying straight towards the targets in order of discovery on the radio. It also has a limited max speed to avoid flying out of bounds. It shoots asteroids that are in the way, so it does not get stuck.

@rlane this is still quite raw, let me know what you think.

**Comment by rlane** [comment]
The "Load Solution" button didn't work for me. I didn't have any issues where the first run of the simulation didn't work, though.

Rather than having ships at each target send their own position on a random channel, we could have a single ship send the target positions on separate radios and channels every tick. I'd suggest a Cruiser sitting at the edge of the map since it already has 8 radios. I think the trick will be to put it on a team with no TeamController so that the radio state set by the scenario isn't overridden.

We can give the player a fully featured fighter instead of one without radar and missiles.

**Comment by t-fi** [comment]
Yes, the player should have a normal fighter, after all radar is most of the fun on this scenario! That's fixed now.

The solution was not properly linked, that's also fixed.

Your idea to use a cruiser solves the tick order: Setting the cruiser sent data inside the scenario tick works out fine. No need for enemy AI or anything about the TeamControllers. I believe TeamControllers have no influence anyways, radar appears to be purely based on ships and does not care about teams at all.

I also reduced the asteroid count a little, maybe more asteroids would be more of a challenge. Larger asteroids would be nice, but that has deep implications for the game mechanics. Right now radar cannot tell the size of objects, only location. There are many ways to incorporate size, maybe a deep scan that returns the full polygon plus all kinematics (position, velocity, heading, angular velocity)?

https://github.com/rlane/oort3/assets/16362866/9d4a2275-01d4-4c8f-9302-b04be9ee3cd7

**Comment by rlane** [comment]
Looks good, I'll merge it now and we can iterate on the asteroid size / density.

**Pull request merged**
